kms:
  location: us-central1
  keyring: cloudbuild
  key: github
encryptedWebhookSecret: CiQAxdYgHOu3ial9i9ftkxR2XwprrnAaY36v8tBdtTHKauE7CqkSPQA/OpLBGXXVDaMcxnvrg6jC66mOVdf2hJ9hdtYfFQAAJ3Mv2OGjP9UBrWt2D/Tu44/0Vfu0d+Ucydqedjc=
repos:
  curioswitch/curiostack:
    encryptedGithubToken: CiQAxdYgHDuRRvjwSuQcIStYUcnzyCw4RBU3MyN0RLhf8VNB9KwSUQA/OpLB5Nz5gDxEa3QguSGKcgC6avYQutsKRfXwXAU0P1Sh26n96IIFtEFIzOsZrB2S9/eX1rmoMNgNvYFG2Q3ZkG+mFM9ADCLAlNwCO23iDw==
    cloudbuild:
      steps:
        - id: fetch-source
          name: gcr.io/cloud-builders/gcloud
          entrypoint: bash
          args:
            - '-c'
            - |
              echo 'echo $$GITHUB_TOKEN' > /tmp/cloudbuild-github-pass.sh && \
              chmod +x /tmp/cloudbuild-github-pass.sh && \
              git init && \
              git fetch --no-tags --progress $_REPOSITORY_URL +$_OTHER_BRANCH_REMOTE_REF:$_OTHER_BRANCH_LOCAL_REF +$_BASE_BRANCH_REMOTE_REF:$_BASE_BRANCH_LOCAL_REF && \
              git config remote.origin.url $_REPOSITORY_URL && \
              git config user.name cloudbuild && \
              git config user.email cloudbuild@example.com && \
              git checkout -f $_OTHER_BRANCH_LOCAL_REF && \
              git merge --no-ff --no-edit --no-progress $_BASE_BRANCH_LOCAL_REF && \
              MERGE_REV=$(git rev-parse HEAD^{commit}) && \
              git checkout -f $_BASE_BRANCH_LOCAL_REF && \
              git merge --no-ff --no-edit --no-progress $$MERGE_REV && \
              MERGE_REV=$(git rev-parse HEAD^{commit}) && \
              git checkout -f $$MERGE_REV
          env:
            - GIT_ASKPASS=/tmp/cloudbuild-github-pass.sh
          secretEnv:
            - GITHUB_TOKEN
        - id: build-all
          name: gcr.io/$PROJECT_ID/java-cloud-builder
          entrypoint: ./gradlew
          args:
            - continuousTest
            - '--stacktrace'
            - '--no-daemon'
          env:
            - CI=true
      timeout: 60m
      secrets:
        - kmsKeyName: projects/curioswitch-cluster/locations/us-central1/keyRings/cloudbuild/cryptoKeys/github
          secretEnv:
            GITHUB_TOKEN: CiQAxdYgHDuRRvjwSuQcIStYUcnzyCw4RBU3MyN0RLhf8VNB9KwSUQA/OpLB5Nz5gDxEa3QguSGKcgC6avYQutsKRfXwXAU0P1Sh26n96IIFtEFIzOsZrB2S9/eX1rmoMNgNvYFG2Q3ZkG+mFM9ADCLAlNwCO23iDw==
